//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileClip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileClip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Using Connection sqlite from Configuration file C:\TFS\FileClip\Migrations\bin\Debug\Migrations.dll.config */
        ////* VersionMigration migrating ================================================ */
        ///
        ////* CreateTable VersionInfo */
        ///CREATE TABLE &quot;VersionInfo&quot; (&quot;Version&quot; INTEGER NOT NULL)
        ///
        ////* VersionMigration migrated */
        ///
        ////* VersionUniqueMigration migrating ========================================== */
        ///
        ////* CreateIndex VersionInfo (Version) */
        ///CREATE UNIQUE INDEX &quot;UC_Version&quot; ON &quot;VersionInfo&quot; (&quot;Version&quot; A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbSqlite {
            get {
                return ResourceManager.GetString("dbSqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Using Connection sqlserver from Configuration file C:\TFS\FileClip\Migrations\bin\Debug\Migrations.dll.config */
        ////* VersionMigration migrating ================================================ */
        ///
        ////* Beginning Transaction */
        ////* CreateTable VersionInfo */
        ///CREATE TABLE [dbo].[VersionInfo] ([Version] BIGINT NOT NULL)
        ///
        ////* Committing Transaction */
        ////* VersionMigration migrated */
        ///
        ////* VersionUniqueMigration migrating ========================================== */
        ///
        ////* Beginning Transaction */
        ////* Crea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbSqlServer {
            get {
                return ResourceManager.GetString("dbSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ScriptSql {
            get {
                return ResourceManager.GetString("ScriptSql", resourceCulture);
            }
        }
    }
}
